POST http://localhost:8080/events/1/register
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1haWwyQHRlc3QuY29tIiwiZXhwIjoxNzM1NTM3ODU3LCJ1c2VySWQiOjJ9.csD6ItNO-LSUueRExzIb8ONu1NjwOK9mEe0IufGdoKw


